
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import 'remixicon/fonts/remixicon.css';
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import WhatsAppButton from "@/app/components/WhatsAppButton";
import { AppContextProvider } from "./context/AppContext";
import CustomToaster from "./components/CustomToaster";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Haddi Fast Foods",
  description: "Generated by danish",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <AppContextProvider>

          <Navbar />
          {children}
          <WhatsAppButton />
          <CustomToaster />
        </AppContextProvider>
      </body>
    </html>
  );
}
