import { Geist, Geist_Mono } from "next/font/google";
import 'remixicon/fonts/remixicon.css';
import "./globals.css";
import Breadcrumbs from "@/app/components/Breadcrumbs";
import { AppContextProvider } from "./context/AppContext";
import CustomToaster from "./components/CustomToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Haddi Fast Foods",
  description: "Generated by danish",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider>
          
        <Breadcrumbs/>
        {children}
        <CustomToaster/>
        </AppContextProvider>
      </body>
    </html>
  );
}
